### ISSUE TITLE
License inquiry 

### ISSUE THREAD

**Issue by mshuaibii** [MPA2suite/autoWTE#4]
Awesome work! Any chance to make this accessible under a more permissive license? We were interested in reproducing the new results on https://matbench-discovery.materialsproject.org/ with our models but the current license prohibits this. 

Thanks!

**Comment by MSimoncelli** [comment]
Thank you for the positive feedback! We are pleased to read that you find our work of interest. We are working to address your question. We will provide updates as soon as possible (and no later than the end of the week). Thank you for your patience.

**Comment by MSimoncelli** [comment]
Dear Muhammed Shuaibi,

We are honored that FAIR Meta AI is interested in this work, and we are very grateful for your efforts in publicly releasing the EquiformerV2 models you developed. As such, we are pleased to offer free access to our code for a 6-month period under an evaluation license.

If this licensing scheme is of interest to your company, please contact me at ms2855@cam.ac.uk, and we will provide all the details. We believe this period should be sufficient for reproducing the new results on https://matbench-discovery.materialsproject.org/, but we are also open to discussing extensions or alternative licensing arrangements.

Thank you again for your interest. We look forward to hearing from you.

Best regards,
Michele Simoncelli, on behalf of all developers

**Comment by mshuaibii** [comment]
An exclusive license for an "open" benchmark is still not the right move here for community reproducibility beyond just our team. We'll wait until hopefully another workaround comes to light. Please keep me posted, thanks!

**Comment by MSimoncelli** [comment]
Following this request, we have just released a benchmark-only code under the GPL-3.0 license:
https://github.com/MPA2suite/k_SRME.git

**Comment by kyonofx** [comment]
> Following this request, we have just released a benchmark-only code under the GPL-3.0 license: https://github.com/MPA2suite/k_SRME.git

Thanks for the effort!
